use std::path::PathBuf;

use iced::{keyboard, window};

use crate::app::OperationResult;
#[derive(Debug, Clone)]
pub(crate) enum Message {
    VaultPathChanged(String),
    PasswordChanged(String),
    ImportPathChanged(String),
    ExportPathChanged(String),
    SearchChanged(String),
    NewFolderNameChanged(String),
    RenameNameChanged(String),
    CycleSortMode,
    CycleImportConflictPolicy,
    CycleFailurePolicy,
    PickVaultFolder,
    PickImportFile,
    PickImportFolder,
    PickExportFolder,
    PickedVaultFolder(Option<PathBuf>),
    PickedImportPath(Option<PathBuf>),
    PickedExportFolder(Option<PathBuf>),
    UseVaultRecord(String),
    RemoveVaultRecord(String),
    RevealVaultFolder(String),
    RefreshVaultRecords,
    NavigateTo(String),
    NavigateUp,
    SelectEntry(String),
    CreateVault,
    OpenVault,
    LockVault,
    ImportPath,
    ExportAll,
    ExportSelected,
    CreateFolder,
    RenameSelected,
    HealthCheck,
    CleanupOrphans,
    CleanupOrphansConfirmed(bool),
    ExportHealthReport,
    OpenVaultFolder,
    ShowChangePassword,
    HideChangePassword,
    OldPasswordChanged(String),
    NewPasswordChanged(String),
    NewPasswordConfirmChanged(String),
    ChangePassword,
    MoveDestinationChanged(String),
    RequestMoveSelected,
    MoveSelectedConfirmed(bool),
    CancelMove,
    RequestDeleteSelected,
    DeleteSelectedConfirmed(bool),
    RequestCancelOperation,
    CancelOperationConfirmed(bool),
    ProgressTick,
    CloseRequested(window::Id),
    CloseRequestConfirmed(window::Id, bool),
    OperationFinished(OperationResult),
    ModifiersChanged(keyboard::Modifiers),
    RightClickEntry(String),
    PickedRightClickMoveDest(String, String),
    CancelRightClickMove,
}
